---
# NOTE: this deployment works with the "toolforge" Kubernetes cluster, and not the legacy "default" cluster.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel.queue
  namespace: tool-wikicrowd
  labels:
    name: laravel.queue
    # The toolforge=tool label will cause $HOME and other paths to be mounted from Toolforge
    toolforge: tool
spec:
  replicas: 1
  selector:
    matchLabels:
      name: laravel.queue
      toolforge: tool
  template:
    metadata:
      labels:
        name: laravel.queue
        toolforge: tool
    spec:
      containers:
        - name: queue
          image: docker-registry.tools.wmflabs.org/toolforge-php74-sssd-base:latest
          command: [ "php", "/data/project/wikicrowd/src/artisan", "queue:work" ]
          workingDir: /data/project/wikicrowd
          env:
            - name: HOME
              value: /data/project/wikicrowd
          imagePullPolicy: Always
